apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.productsService.name }}-config
  namespace: {{ .Values.namespace }}
data:
  APP_ENV: {{ .Values.productsService.env.APP_ENV | quote }}
  PORT: {{ .Values.productsService.env.PORT | quote }}
  SERVICE_A_URL: "http://{{ .Values.ordersService.name }}:{{ .Values.ordersService.port }}"
